### PR TITLE
Fix blank nav element and extra content page that is generated

### PR DESCRIPTION
**Pull request by cmulk**

### CODE REVIEW

**Comment by andrewbanchich** [comment]
Thanks!

**Comment by cmulk** [comment]
Did this get reverted? I'm seeing the blank nav elements back again and the merged commits are no longer there

**Comment by andrewbanchich** [comment]
It may have accidentally been undone when I set up mirroring from the GitLab repository a few days ago... Sorry about that. I will add it back this weekend.

I've been trying to centralize where the code and merge requests originate from so I decided on GitLab as the source mirroring to GitHub.

**Comment by cmulk** [comment]
No worries at all I was just using it again this weekend and thought I was
going crazy!

**Comment by andrewbanchich** [comment]
Should be back now. Let me know if that works.

Thanks for the heads up!

**Pull request merged**
